import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className='min-h-screen text-gray-800'>
      <Head>
        <title>Formie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-karla  max-w-lg mx-auto mt-16 md:mb-48 space-y-24'>
        <div className='flex flex-col items-center'>
          {/* <header className='flex items-center justify-between w-full mb-12'>
            <div className='flex justify-center items-center h-9 w-8 p-1 rounded-md bg-blue-500'>
              <div className='text-white italic font-lora font-medium text-2xl'>F</div>
            </div>
            <div className='flex items-center'>
              <p className='text-gray-500 mr-4'>Log in</p>
            </div>
          </header> */}
            <div className='mb-12 flex justify-center items-center h-9 w-8 p-1 rounded-md bg-blue-500'>
              <div className='text-white italic font-lora font-medium text-2xl'>F</div>
            </div>
          <h1 className='font-lora text-4xl font-medium text-center mb-12'>Turn Smart Contracts into Forms</h1>
          <Link href="/new">
            <button className="cursor-default h-min tracking-tight bg-blue-500 transition duration-200 hover:bg-blue-600 focus:ring-2 focus:ring-blue-500 hover:text-blue-50 py-2 px-4 rounded-lg font-medium text-white">Make a form</button>
          </Link>
          <div className='flex items-center mt-4'>
            <p className='text-gray-500  text-sm'>Log in</p>
          </div>
        </div>
        <h2 className='font-lora text-2xl text-center mb-6'>Mint from Etherscan? No thanks.</h2>
        {/* <article className='space-y-4'>
          <p>Have you seen it before? It's disgusting — look:</p>
          <p>It's an abomanation, a total trainwreak of an experinece.</p>
          <p>WTF's a <code>uint256</code>?.</p>
        </article> */}
      </main>
    </div>
  )
}
