import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useAccount } from 'wagmi'
import { shortenAddress } from '../utils/helpers'
import { ArrowSmUpIcon } from '@heroicons/react/outline'
import { ChevronDownIcon } from '@heroicons/react/solid'
import WalletConnectButton from '../components/WalletConnectButton'
import LogInWalletConnectButton from '../components/LogInWalletConnectButton'

import { findUser, createUser } from '../lib/db'
import { useEffect } from 'react'
import Router from 'next/router'

export default function Home() {
  const { data, isError, isLoading, isSuccess } = useAccount()
  const { address, connector } = data || {}

  const handleLogin = () => {
    if (address) {
      const user = findUser(address);
      if (!user) {
        createUser(address)
        Router.push('/new');
        return;
      }
      if (!user.forms) {
        Router.push('/new');
        return;
      }
      Router.push(`/${address}`);
      return;
    }
  }

  useEffect(() => {
    if (address) {
      const user = findUser(address);
      if (!user) {
        createUser(address)
        Router.push('/new');
        return;
      }
      if (!user.forms) {
        Router.push('/new');
        return;
      }
      Router.push(`/${address}`);
      return;
    }
  }, [isSuccess]);

  const loginBtn = () => (
    <button onClick={handleLogin} className={`${address ? 'hidden' : ''} text-base font-medium py-2 px-4 hover:bg-blue-600 rounded-lg`}>
      Log in
    </button>
  );

  return (
    <div className='min-h-screen text-white bg-blue-500'>
      <Head>
        <title>Formie</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className='font-lora max-w-6xl mx-auto pb-48'>
        <div>
          <header className='mx-8 z-50 flex items-center justify-between pt-8 pb-16 md:pb-12 w-full'>
            <div className='flex justify-center items-center h-9 w-8 p-1 rounded-md bg-blue-400 shadow-sm'>
              <div className='drop-shadow italic font-lora font-medium text-2xl'>F</div>
            </div>
            <div className='flex space-x-2'>
              <LogInWalletConnectButton 
                label={'Connect wallet'} 
                classes={'font-karla font-medium text-white'}
                isDropdown={true}
                isWhite={true}
              />
              {address && (
                <button onClick={handleLogin} className={`text-base font-medium py-2 px-4 hover:bg-blue-600 rounded-lg`}>
                  Log in
                </button>
              )}
            </div>
          </header>
          <main className='max-w-3xl mx-auto'>
            <section className='flex flex-col items-center space-y-16 sm:space-y-20'>
              <div className='mx-8 flex flex-col items-center space-y-8 md:space-y-12'>
                <h1 className='font-lora text-4xl sm:text-5xl md:text-6xl md:leading-[4.25rem] font-medium text-center'>Turn <i>any</i> smart contract into a form</h1>
                <LogInWalletConnectButton label={'Make a form (in 5 mins)'} classes={'w-fit font-karla cursor-default h-min tracking-tight bg-[#1E6FF6] transition duration-200 hover:bg-blue-600 focus:ring-2 focus:ring-blue-500 hover:text-blue-50 py-2 px-4 rounded-lg font-medium text-white'} />
              </div>

              <img 
                src='/forms.png'
                alt='Forms'
                className='mx-8 w-full max-w-2xl h-auto mb-4'
              />
              <span className='w-px h-12 border border-blue-400'></span>
              <div className='flex flex-col items-center space-y-8 mt-8 w-full max-w-xl'>
                <h3 className='font-lora text-3xl font-medium text-center'>See them for yourself</h3>
                <section className='sm:mx-8 bg-white border-blue-400 sm:rounded-xl w-full -mx-8 sm:px-0 sm:shadow-xl'>
                  <article className='w-full group flex items-center justify-between text-gray-800 py-7 px-8 sm:px-10 border-b hover:bg-gray-100 rounded-t-xl transition duration-200'>
                    <div className='w-full space-y-6'>
                      <h3 className='font-lora text-xl font-medium'>Swap a Token on Uniswap</h3> 
                      <div className='flex '>
                        <div className='flex-1 mr-4'>
                          <h4 className='uppercase text-xs text-gray-400 tracking-wider font-karla mb-1 whitespace-nowrap'>Contract</h4>
                          <h2 className='text-base break-all leading-6'>Uniswap</h2>
                        </div>
                        <div className='flex-1 mr-4'>
                          <h4 className='uppercase text-xs text-gray-400 tracking-wider font-karla mb-1 whitespace-nowrap'>Method</h4>
                          <p className='text-base break-all leading-6'>swap</p>
                        </div>
                      </div>
                    </div>
                    <ArrowSmUpIcon className='h-6 w-6 transform rotate-45 group-hover:translate-x-1 group-hover:-translate-y-1 transition duration-200 text-gray-400 group-hover:text-gray-500' />
                  </article>
                  <article className='group flex items-center justify-between text-gray-800 py-7 px-8 sm:px-10 border-b hover:bg-gray-100 rounded-t-xl transition duration-200'>
                    <div className='w-full space-y-6'>
                      <h3 className='font-lora text-xl font-medium'>Swap a Token on Uniswap</h3> 
                      <div className='flex '>
                        <div className='flex-1 mr-4'>
                          <h4 className='uppercase text-xs text-gray-400 tracking-wider font-karla mb-1 whitespace-nowrap'>Contract</h4>
                          <h2 className='text-base break-all leading-6'>Uniswap</h2>
                        </div>
                        <div className='flex-1 mr-4'>
                          <h4 className='uppercase text-xs text-gray-400 tracking-wider font-karla mb-1 whitespace-nowrap'>Method</h4>
                          <p className='text-base break-all leading-6'>swap</p>
                        </div>
                      </div>
                    </div>
                    <ArrowSmUpIcon className='h-6 w-6 transform rotate-45 group-hover:translate-x-1 group-hover:-translate-y-1 transition duration-200 text-gray-400 group-hover:text-gray-500' />
                  </article>
                  <article className='group flex items-center justify-between text-gray-800 py-7 px-8 sm:px-10 border-b hover:bg-gray-100 rounded-t-xl transition duration-200'>
                    <div className='w-full space-y-6'>
                      <h3 className='font-lora text-xl font-medium'>Swap a Token on Uniswap</h3> 
                      <div className='flex '>
                        <div className='flex-1 mr-4'>
                          <h4 className='uppercase text-xs text-gray-400 tracking-wider font-karla mb-1 whitespace-nowrap'>Contract</h4>
                          <h2 className='text-base break-all leading-6'>Uniswap</h2>
                        </div>
                        <div className='flex-1 mr-4'>
                          <h4 className='uppercase text-xs text-gray-400 tracking-wider font-karla mb-1 whitespace-nowrap'>Method</h4>
                          <p className='text-base break-all leading-6'>swap</p>
                        </div>
                      </div>
                    </div>
                    <ArrowSmUpIcon className='h-6 w-6 transform rotate-45 group-hover:translate-x-1 group-hover:-translate-y-1 transition duration-200 text-gray-400 group-hover:text-gray-500' />
                  </article>
                </section>
              </div>
              
            </section>
          </main>
        </div>
      </div>
    </div>
  )
}
